//==============================================================================
//  STATUS CONSTANTS
//==============================================================================
/** @class */
net.user1.orbiter.Status = new Object();
/** @constant */
net.user1.orbiter.Status.ACCOUNT_EXISTS         = "ACCOUNT_EXISTS";
/** @constant */
net.user1.orbiter.Status.ACCOUNT_NOT_FOUND      = "ACCOUNT_NOT_FOUND";
/** @constant */
net.user1.orbiter.Status.AUTHORIZATION_REQUIRED = "AUTHORIZATION_REQUIRED";
/** @constant */
net.user1.orbiter.Status.AUTHORIZATION_FAILED   = "AUTHORIZATION_FAILED";
/** @constant */
net.user1.orbiter.Status.ALREADY_ASSIGNED       = "ALREADY_ASSIGNED";
/** @constant */
net.user1.orbiter.Status.ALREADY_BANNED         = "ALREADY_BANNED";
/** @constant */
net.user1.orbiter.Status.ALREADY_IN_ROOM        = "ALREADY_IN_ROOM";
/** @constant */
net.user1.orbiter.Status.ALREADY_LOGGED_IN      = "ALREADY_LOGGED_IN";
/** @constant */
net.user1.orbiter.Status.ALREADY_OBSERVING      = "ALREADY_OBSERVING";
/** @constant */
net.user1.orbiter.Status.ALREADY_SYNCHRONIZED   = "ALREADY_SYNCHRONIZED";
/** @constant */
net.user1.orbiter.Status.ALREADY_WATCHING       = "ALREADY_WATCHING";  
/** @constant */
net.user1.orbiter.Status.ATTR_NOT_FOUND         = "ATTR_NOT_FOUND";
/** @constant */
net.user1.orbiter.Status.CLIENT_NOT_FOUND       = "CLIENT_NOT_FOUND";
/** @constant */
net.user1.orbiter.Status.ERROR                  = "ERROR";
/** @constant */
net.user1.orbiter.Status.EVALUATION_FAILED      = "EVALUATION_FAILED";
/** @constant */
net.user1.orbiter.Status.DUPLICATE_VALUE        = "DUPLICATE_VALUE";
/** @constant */
net.user1.orbiter.Status.IMMUTABLE              = "IMMUTABLE";
/** @constant */
net.user1.orbiter.Status.INVALID_QUALIFIER      = "INVALID_QUALIFIER";
/** @constant */
net.user1.orbiter.Status.NAME_NOT_FOUND         = "NAME_NOT_FOUND";
/** @constant */
net.user1.orbiter.Status.NAME_EXISTS            = "NAME_EXISTS";
/** @constant */
net.user1.orbiter.Status.NOT_ASSIGNED           = "NOT_ASSIGNED";
/** @constant */
net.user1.orbiter.Status.NOT_BANNED             = "NOT_BANNED";
/** @constant */
net.user1.orbiter.Status.NOT_IN_ROOM            = "NOT_IN_ROOM";
/** @constant */
net.user1.orbiter.Status.NOT_LOGGED_IN          = "NOT_LOGGED_IN";
/** @constant */
net.user1.orbiter.Status.NOT_OBSERVING          = "NOT_OBSERVING";
/** @constant */
net.user1.orbiter.Status.NOT_WATCHING           = "NOT_WATCHING";
/** @constant */
net.user1.orbiter.Status.PERMISSION_DENIED      = "PERMISSION_DENIED";
/** @constant */
net.user1.orbiter.Status.REMOVED                = "REMOVED";
/** @constant */
net.user1.orbiter.Status.ROLE_NOT_FOUND         = "ROLE_NOT_FOUND";
/** @constant */
net.user1.orbiter.Status.ROOM_EXISTS            = "ROOM_EXISTS";
/** @constant */
net.user1.orbiter.Status.ROOM_FULL              = "ROOM_FULL";
/** @constant */
net.user1.orbiter.Status.ROOM_NOT_FOUND         = "ROOM_NOT_FOUND";
/** @constant */
net.user1.orbiter.Status.SERVER_ONLY            = "SERVER_ONLY";
/** @constant */
net.user1.orbiter.Status.SUCCESS                = "SUCCESS";
